# Generated by Django 3.2.4 on 2022-05-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0002_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='last_poster_name',
        ),
    ]
