# Generated by Django 3.2.4 on 2022-05-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0003_remove_thread_last_poster_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
