# Generated by Django 3.2.4 on 2022-05-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0005_alter_reply_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='replies',
            field=models.CharField(default='', max_length=200),
        ),
    ]
