# Generated by Django 3.2.4 on 2022-05-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0006_thread_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='replies',
        ),
    ]
